### ISSUE TITLE
Currency Conversions Optimization

### ISSUE THREAD

**Issue by hauxir** [hauxir/OpenBazaar-Client#1]
Here's a small task you guys can do that would be very helpful:

In js/utils/getBitcoinPrice.js, we take the user's local currency, and run it through several APIs to get the Bitcoin value of that currency. We do this because any given API might be down, or have changed how it works, that way as long as one of them is still working the client doesn't fail.

Getting the price for each item individually is inefficient. One of our todos is to put a timestamp on each currency check, and if that currency has been retrieved within the last 15 minutes, used the stored value instead.

My suggestion is to put an array of retrieved currency conversions and timestamps into a global object*,  and if the currency being checked is in that object, and the timestamp is less than 15 minutes old, use it instead of getting a new average price.

*generally global objects are to be avoided, in this case it's ok, and a lot simpler than creating a backbone model to store the data which we have to pass around to different views.

The global object might be something like:

window.bitcoinAverageCache = {USD : {timeInMilliseconds: 1111111111111, AveragePrice: 200},  EUR: {timeInMilliseconds: 123123123131221, AveragePrice: 300}}

**Comment by hauxir** [comment]
@Awarath @plankt @markm1992 @JCLengeling @gpseiridis

**Comment by hauxir** [comment]
If you want a more complicated task, we've also considered changing how this works, so instead of doing an individual query per currency, changing to the APIs that return a list of all currencies, averaging the ones available (not all APIs return all the currencies), and keeping that as a global object with all currencies, which gets updated if it's checked and more than 15 minutes old.

joshj [4:24 PM]
That would be a little more work to parse, but would cut down on the API calls considerably.

**Comment by hauxir** [comment]
OK I took a little look at it.
To do the "more complicated task" i checked out the API's a bit.
We would have to use
https://api.bitcoinaverage.com/all
for bitcoin average. Thing is, it only returns the average the last 24hours instead of 15mins like they do when you ask for individual currencies. Guess we have to ask OB guys if that's good enough.

Coindesk doesn't support requesting multiple currencies at a time so perhaps we can drop that one. Also have to ask OB guys if that's OK.

Blockchain supports multiple currencies, very small changes need to be done to make use of that.
The same with Coinkite.

**Comment by hauxir** [comment]
never mind about bitcoinaverage, they always just return the 24h average

**Comment by hauxir** [comment]
We should have at least 4 APIs we're hitting, the risk several of them will be down at any given time is too high. Look around to see if there are other APIs we can use that don't require logging in or other steps that are incompatible with how OB works. 

There's also the option of doing things in a more complicated manner, like so:
1. when a price is requested for the first time, get all currencies from the 1st 3 APIs, get only the requested currency from Coindesk, and store them in a global object with 2 child objects {allprices: {currencyCode: averagePrice, currencyCode: averagePrice, etc}, coinDesk: {currencyCode: price, currencyCode: price}, timeStamp: timeInMilliseconds}.
2. create an average from the averagePrice value in the allprices child object and the price in the coinDesk child object.

Then, when the next price is requested, if it already exists in the coinDesk object, and it's less than 15 minutes old, run the average with the two values, otherwise call Coindesk only for a new average price for that currency, and add it to the coinDesk object. 

That would be a little clunky, but it should work.

**Comment by markm1992** [comment]
That sounds good, Seems like it's a viable solution that should be good enough for OB. 

```
 On Sunday, September 20, 2015 11:36 AM, Haukur Rosinkranz <notifications@github.com> wrote:
```

 We should have at least 4 APIs we're hitting, the risk several of them will be down at any given time is too high. Look around to see if there are other APIs we can use that don't require logging in or other steps that are incompatible with how OB works. There's also the option of doing things in a more complicated manner, like so:   
- when a price is requested for the first time, get all currencies from the 1st 3 APIs, get only the requested currency from Coindesk, and store them in a global object with 2 child objects {allprices: {currencyCode: averagePrice, currencyCode: averagePrice, etc}, coinDesk: {currencyCode: price, currencyCode: price}, timeStamp: timeInMilliseconds}.
- create an average from the averagePrice value in the allprices child object and the price in the coinDesk child object.
  Then, when the next price is requested, if it already exists in the coinDesk object, and it's less than 15 minutes old, run the average with the two values, otherwise call Coindesk only for a new average price for that currency, and add it to the coinDesk object. That would be a little clunky, but it should work.—

**Comment by hauxir** [comment]
This one seems to be a good replacement for Coindesk:
http://api.bitcoincharts.com/v1/markets.json

**Comment by jjeffryes** [comment]
Bitcoincharts should work, double check that they don't have any requirements for their api that would be an issue. The 1 call per 15 minutes limitation should be OK.

**Comment by markm1992** [comment]
Bitcoincharts is a list of the latest bids for currencies and market information. We would have to pull all the usd data and average it, which still may not be reliable because some of the bids are just way off. For example the average is 257 usd to bitcoins when really it is about 233.

**Comment by hauxir** [comment]
The link above was incorrect, sorry about that, this one seems to be the correct one:
http://api.bitcoincharts.com/v1/weighted_prices.json
